description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install --frozen-lockfile
      shell: bash
  using: composite
