jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: npm run format --list-different

name: Format

on:
  pull_request: ~
  push:
    branches:
      - master
